/*
 * codegen.c — Code generation for soft chips
 *
 * Part of TriX toolchain
 * Generates C and NEON code from SoftChipSpec
 */

#include "../include/codegen.h"
#include "../include/linear_forge.h"
#include <string.h>
#include <ctype.h>
#include <time.h>
#include <sys/stat.h>

static const char* TARGET_NAMES[] = {
    "c", "neon", "avx2", "avx512", "wasm", "verilog"
};

const char* target_name(CodegenTarget target) {
    if (target >= 0 && target < TARGET_COUNT) {
        return TARGET_NAMES[target];
    }
    return "unknown";
}

CodegenTarget target_from_name(const char* name) {
    for (int i = 0; i < TARGET_COUNT; i++) {
        if (strcasecmp(name, TARGET_NAMES[i]) == 0) {
            return (CodegenTarget)i;
        }
    }
    return TARGET_C;  /* Default */
}

void codegen_options_init(CodegenOptions* opts) {
    opts->target = TARGET_C;
    opts->generate_test = true;
    opts->generate_bench = false;
    opts->optimize = true;
    opts->output_dir = "output";
}

/* Generate timestamp string */
static void get_timestamp(char* buf, size_t size) {
    time_t now = time(NULL);
    struct tm* t = localtime(&now);
    strftime(buf, size, "%Y-%m-%d %H:%M:%S", t);
}

/* Generate the header file */
int generate_header_file(const SoftChipSpec* spec, const CodegenOptions* opts,
                         const char* filename) {
    FILE* f = fopen(filename, "w");
    if (!f) return -1;

    char timestamp[64];
    get_timestamp(timestamp, sizeof(timestamp));

    char upper_name[MAX_NAME_LEN];
    for (int i = 0; spec->name[i] && i < MAX_NAME_LEN - 1; i++) {
        upper_name[i] = toupper(spec->name[i]);
        upper_name[i+1] = '\0';
    }

    fprintf(f, "/*\n");
    fprintf(f, " * %s.h — Soft Chip: %s\n", spec->name, spec->name);
    fprintf(f, " *\n");
    fprintf(f, " * Auto-generated by trix forge\n");
    fprintf(f, " * Generated: %s\n", timestamp);
    fprintf(f, " * Target: %s\n", target_name(opts->target));
    fprintf(f, " *\n");
    fprintf(f, " * DO NOT EDIT — Regenerate from .trix spec\n");
    fprintf(f, " */\n\n");

    fprintf(f, "#ifndef %s_H\n", upper_name);
    fprintf(f, "#define %s_H\n\n", upper_name);

    fprintf(f, "#include <stdint.h>\n");
    fprintf(f, "#include <stddef.h>\n\n");

    fprintf(f, "/* State size */\n");
    fprintf(f, "#define %s_STATE_BITS  %d\n", upper_name, spec->state_bits);
    fprintf(f, "#define %s_STATE_BYTES %d\n\n", upper_name, spec->state_bits / 8);

    fprintf(f, "/* Signature labels */\n");
    for (int i = 0; i < spec->num_signatures; i++) {
        char upper_sig[MAX_NAME_LEN];
        for (int j = 0; spec->signatures[i].name[j] && j < MAX_NAME_LEN - 1; j++) {
            upper_sig[j] = toupper(spec->signatures[i].name[j]);
            upper_sig[j+1] = '\0';
        }
        fprintf(f, "#define %s_%s %d\n", upper_name, upper_sig, i);
    }
    fprintf(f, "#define %s_UNKNOWN -1\n\n", upper_name);

    fprintf(f, "/* Soft chip handle */\n");
    fprintf(f, "typedef struct trix_chip trix_chip_t;\n\n");

    fprintf(f, "/* Inference result */\n");
    fprintf(f, "typedef struct {\n");
    fprintf(f, "    int match;          /* Signature index (-1 = no match) */\n");
    fprintf(f, "    int distance;       /* Hamming distance to match */\n");
    fprintf(f, "    int threshold;      /* Threshold that was used */\n");
    fprintf(f, "    const char* label;  /* Human-readable label */\n");
    fprintf(f, "} trix_result_t;\n\n");

    fprintf(f, "/* API */\n");
    fprintf(f, "trix_chip_t* trix_init(void);\n");
    fprintf(f, "trix_result_t trix_infer(trix_chip_t* chip, const uint8_t input[%d]);\n",
            spec->state_bits / 8);
    fprintf(f, "void trix_reset(trix_chip_t* chip);\n");
    fprintf(f, "void trix_free(trix_chip_t* chip);\n\n");

    fprintf(f, "/* State access (for debugging) */\n");
    fprintf(f, "const uint8_t* trix_get_state(const trix_chip_t* chip);\n\n");

    fprintf(f, "#endif /* %s_H */\n", upper_name);

    fclose(f);
    return 0;
}

/* Generate popcount function */
static void emit_popcount(FILE* f, CodegenTarget target) {
    if (target == TARGET_NEON) {
        fprintf(f, "/* NEON popcount for 512 bits */\n");
        fprintf(f, "#include <arm_neon.h>\n\n");
        fprintf(f, "static inline int popcount_512_neon(const uint8_t* a, const uint8_t* b) {\n");
        fprintf(f, "    int count = 0;\n");
        fprintf(f, "    for (int i = 0; i < 64; i += 16) {\n");
        fprintf(f, "        uint8x16_t va = vld1q_u8(a + i);\n");
        fprintf(f, "        uint8x16_t vb = vld1q_u8(b + i);\n");
        fprintf(f, "        uint8x16_t vxor = veorq_u8(va, vb);\n");
        fprintf(f, "        uint8x16_t vcnt = vcntq_u8(vxor);\n");
        fprintf(f, "        count += vaddvq_u8(vcnt);\n");
        fprintf(f, "    }\n");
        fprintf(f, "    return count;\n");
        fprintf(f, "}\n\n");
    } else {
        fprintf(f, "/* Portable popcount for 512 bits */\n");
        fprintf(f, "static inline int popcount_512(const uint8_t* a, const uint8_t* b) {\n");
        fprintf(f, "    int count = 0;\n");
        fprintf(f, "    for (int i = 0; i < 64; i++) {\n");
        fprintf(f, "        uint8_t x = a[i] ^ b[i];\n");
        fprintf(f, "        /* Portable popcount */\n");
        fprintf(f, "        x = x - ((x >> 1) & 0x55);\n");
        fprintf(f, "        x = (x & 0x33) + ((x >> 2) & 0x33);\n");
        fprintf(f, "        count += (x + (x >> 4)) & 0x0F;\n");
        fprintf(f, "    }\n");
        fprintf(f, "    return count;\n");
        fprintf(f, "}\n\n");
    }
}

/* Generate the source file */
int generate_source_file(const SoftChipSpec* spec, const CodegenOptions* opts,
                         const char* filename) {
    FILE* f = fopen(filename, "w");
    if (!f) return -1;

    char timestamp[64];
    get_timestamp(timestamp, sizeof(timestamp));

    fprintf(f, "/*\n");
    fprintf(f, " * %s.c — Soft Chip: %s\n", spec->name, spec->name);
    fprintf(f, " *\n");
    fprintf(f, " * Auto-generated by trix forge\n");
    fprintf(f, " * Generated: %s\n", timestamp);
    fprintf(f, " * Target: %s\n", target_name(opts->target));
    fprintf(f, " */\n\n");

    fprintf(f, "#include \"%s.h\"\n", spec->name);
    fprintf(f, "#include <stdlib.h>\n");
    fprintf(f, "#include <string.h>\n\n");

    /* Emit popcount function */
    emit_popcount(f, opts->target);

    /* Signature data */
    fprintf(f, "/* Signature patterns (%d signatures × 64 bytes) */\n", spec->num_signatures);
    fprintf(f, "static const uint8_t SIGNATURES[%d][64] = {\n", spec->num_signatures);
    for (int i = 0; i < spec->num_signatures; i++) {
        fprintf(f, "    /* %s */\n    {", spec->signatures[i].name);
        for (int j = 0; j < 64; j++) {
            if (j > 0) fprintf(f, ",");
            if (j % 16 == 0) fprintf(f, "\n        ");
            fprintf(f, "0x%02x", spec->signatures[i].pattern[j]);
        }
        fprintf(f, "\n    }%s\n", i < spec->num_signatures - 1 ? "," : "");
    }
    fprintf(f, "};\n\n");

    /* Thresholds */
    fprintf(f, "/* Thresholds */\n");
    fprintf(f, "static const int THRESHOLDS[%d] = {", spec->num_signatures);
    for (int i = 0; i < spec->num_signatures; i++) {
        if (i > 0) fprintf(f, ", ");
        fprintf(f, "%d", spec->signatures[i].threshold);
    }
    fprintf(f, "};\n\n");

    /* Labels */
    fprintf(f, "/* Labels */\n");
    fprintf(f, "static const char* LABELS[%d] = {", spec->num_signatures + 1);
    for (int i = 0; i < spec->num_signatures; i++) {
        fprintf(f, "\"%s\", ", spec->signatures[i].name);
    }
    fprintf(f, "\"%s\"};\n\n", spec->default_label);

    /* Chip structure */
    fprintf(f, "/* Chip state */\n");
    fprintf(f, "struct trix_chip {\n");
    fprintf(f, "    uint8_t state[64];  /* 512-bit resonance state */\n");
    fprintf(f, "};\n\n");

    /* Init function */
    fprintf(f, "trix_chip_t* trix_init(void) {\n");
    fprintf(f, "    trix_chip_t* chip = (trix_chip_t*)malloc(sizeof(trix_chip_t));\n");
    fprintf(f, "    if (chip) {\n");
    fprintf(f, "        memset(chip->state, 0, 64);\n");
    fprintf(f, "    }\n");
    fprintf(f, "    return chip;\n");
    fprintf(f, "}\n\n");

    /* Reset function */
    fprintf(f, "void trix_reset(trix_chip_t* chip) {\n");
    fprintf(f, "    memset(chip->state, 0, 64);\n");
    fprintf(f, "}\n\n");

    /* Free function */
    fprintf(f, "void trix_free(trix_chip_t* chip) {\n");
    fprintf(f, "    free(chip);\n");
    fprintf(f, "}\n\n");

    /* Get state function */
    fprintf(f, "const uint8_t* trix_get_state(const trix_chip_t* chip) {\n");
    fprintf(f, "    return chip->state;\n");
    fprintf(f, "}\n\n");

    /* Infer function */
    fprintf(f, "trix_result_t trix_infer(trix_chip_t* chip, const uint8_t input[64]) {\n");
    fprintf(f, "    trix_result_t result = {-1, 512, 0, LABELS[%d]};\n", spec->num_signatures);
    fprintf(f, "\n");
    fprintf(f, "    /* Zit detection: find matching signature */\n");
    fprintf(f, "    for (int i = 0; i < %d; i++) {\n", spec->num_signatures);

    if (opts->target == TARGET_NEON) {
        fprintf(f, "        int distance = popcount_512_neon(input, SIGNATURES[i]);\n");
    } else {
        fprintf(f, "        int distance = popcount_512(input, SIGNATURES[i]);\n");
    }

    fprintf(f, "        if (distance < THRESHOLDS[i]) {\n");
    fprintf(f, "            result.match = i;\n");
    fprintf(f, "            result.distance = distance;\n");
    fprintf(f, "            result.threshold = THRESHOLDS[i];\n");
    fprintf(f, "            result.label = LABELS[i];\n");

    if (spec->mode == MODE_FIRST_MATCH) {
        fprintf(f, "            break;  /* First match mode */\n");
    }

    fprintf(f, "        }\n");
    fprintf(f, "    }\n\n");

    fprintf(f, "    /* Update resonance state: S = S ^ input */\n");
    fprintf(f, "    for (int i = 0; i < 64; i++) {\n");
    fprintf(f, "        chip->state[i] ^= input[i];\n");
    fprintf(f, "    }\n\n");

    fprintf(f, "    return result;\n");
    fprintf(f, "}\n");

    fclose(f);
    return 0;
}

/* Generate test file */
int generate_test_file(const SoftChipSpec* spec, const CodegenOptions* opts,
                       const char* filename) {
    FILE* f = fopen(filename, "w");
    if (!f) return -1;

    char timestamp[64];
    get_timestamp(timestamp, sizeof(timestamp));

    fprintf(f, "/*\n");
    fprintf(f, " * %s_test.c — Test harness for %s\n", spec->name, spec->name);
    fprintf(f, " *\n");
    fprintf(f, " * Auto-generated by trix forge\n");
    fprintf(f, " * Generated: %s\n", timestamp);
    fprintf(f, " */\n\n");

    fprintf(f, "#include \"%s.h\"\n", spec->name);
    fprintf(f, "#include <stdio.h>\n");
    fprintf(f, "#include <string.h>\n");
    fprintf(f, "#include <time.h>\n\n");

    /* Test each signature matches itself */
    fprintf(f, "/* Signature patterns for testing */\n");
    fprintf(f, "static const uint8_t TEST_PATTERNS[%d][64] = {\n", spec->num_signatures);
    for (int i = 0; i < spec->num_signatures; i++) {
        fprintf(f, "    /* %s */\n    {", spec->signatures[i].name);
        for (int j = 0; j < 64; j++) {
            if (j > 0) fprintf(f, ",");
            if (j % 16 == 0) fprintf(f, "\n        ");
            fprintf(f, "0x%02x", spec->signatures[i].pattern[j]);
        }
        fprintf(f, "\n    }%s\n", i < spec->num_signatures - 1 ? "," : "");
    }
    fprintf(f, "};\n\n");

    fprintf(f, "int main(int argc, char** argv) {\n");
    fprintf(f, "    printf(\"\\n\");\n");
    fprintf(f, "    printf(\"╭──────────────────────────────────────────────────────────────╮\\n\");\n");
    fprintf(f, "    printf(\"│  Soft Chip Test: %s", spec->name);
    for (size_t i = strlen(spec->name); i < 41; i++) fprintf(f, " ");
    fprintf(f, "│\\n\");\n");
    fprintf(f, "    printf(\"╰──────────────────────────────────────────────────────────────╯\\n\");\n");
    fprintf(f, "    printf(\"\\n\");\n\n");

    fprintf(f, "    trix_chip_t* chip = trix_init();\n");
    fprintf(f, "    int passed = 0;\n");
    fprintf(f, "    int failed = 0;\n\n");

    fprintf(f, "    printf(\"Signature Validation:\\n\");\n");
    fprintf(f, "    printf(\"─────────────────────\\n\");\n\n");

    /* Test each signature */
    for (int i = 0; i < spec->num_signatures; i++) {
        fprintf(f, "    /* Test: %s */\n", spec->signatures[i].name);
        fprintf(f, "    trix_reset(chip);\n");
        fprintf(f, "    {\n");
        fprintf(f, "        trix_result_t r = trix_infer(chip, TEST_PATTERNS[%d]);\n", i);
        fprintf(f, "        if (r.match == %d) {\n", i);
        fprintf(f, "            printf(\"  ✓ %s: PASS (distance=%%d)\\n\", r.distance);\n",
                spec->signatures[i].name);
        fprintf(f, "            passed++;\n");
        fprintf(f, "        } else {\n");
        fprintf(f, "            printf(\"  ✗ %s: FAIL (got %%s, distance=%%d)\\n\",\n",
                spec->signatures[i].name);
        fprintf(f, "                   r.label, r.distance);\n");
        fprintf(f, "            failed++;\n");
        fprintf(f, "        }\n");
        fprintf(f, "    }\n\n");
    }

    fprintf(f, "    printf(\"\\n\");\n");
    fprintf(f, "    printf(\"Results: %%d passed, %%d failed\\n\", passed, failed);\n");
    fprintf(f, "    printf(\"\\n\");\n\n");

    /* Benchmark */
    fprintf(f, "    /* Benchmark */\n");
    fprintf(f, "    if (argc > 1 && strcmp(argv[1], \"--bench\") == 0) {\n");
    fprintf(f, "        printf(\"Benchmark:\\n\");\n");
    fprintf(f, "        printf(\"──────────\\n\");\n");
    fprintf(f, "        trix_reset(chip);\n");
    fprintf(f, "        int iterations = 1000000;\n");
    fprintf(f, "        clock_t start = clock();\n");
    fprintf(f, "        for (int i = 0; i < iterations; i++) {\n");
    fprintf(f, "            trix_infer(chip, TEST_PATTERNS[0]);\n");
    fprintf(f, "        }\n");
    fprintf(f, "        clock_t end = clock();\n");
    fprintf(f, "        double elapsed = (double)(end - start) / CLOCKS_PER_SEC;\n");
    fprintf(f, "        printf(\"  %%d iterations in %%.3f seconds\\n\", iterations, elapsed);\n");
    fprintf(f, "        printf(\"  %%.2f M inferences/sec\\n\", iterations / elapsed / 1e6);\n");
    fprintf(f, "        printf(\"\\n\");\n");
    fprintf(f, "    }\n\n");

    fprintf(f, "    trix_free(chip);\n");
    fprintf(f, "    return failed > 0 ? 1 : 0;\n");
    fprintf(f, "}\n");

    fclose(f);
    return 0;
}

/* Generate Makefile */
int generate_makefile(const SoftChipSpec* spec, const CodegenOptions* opts,
                      const char* filename) {
    FILE* f = fopen(filename, "w");
    if (!f) return -1;

    fprintf(f, "# Makefile for %s soft chip\n", spec->name);
    fprintf(f, "# Auto-generated by trix forge\n\n");

    if (opts->target == TARGET_NEON) {
        fprintf(f, "CC = gcc\n");
        fprintf(f, "CFLAGS = -O3 -Wall -march=armv8-a+simd\n");
    } else {
        fprintf(f, "CC = gcc\n");
        fprintf(f, "CFLAGS = -O3 -Wall\n");
    }

    fprintf(f, "\n");
    fprintf(f, "all: %s_test\n\n", spec->name);
    fprintf(f, "%s_test: %s.c %s_test.c\n", spec->name, spec->name, spec->name);
    fprintf(f, "\t$(CC) $(CFLAGS) -o $@ %s.c %s_test.c\n\n", spec->name, spec->name);
    fprintf(f, "clean:\n");
    fprintf(f, "\trm -f %s_test\n\n", spec->name);
    fprintf(f, "run: %s_test\n", spec->name);
    fprintf(f, "\t./%s_test\n\n", spec->name);
    fprintf(f, "bench: %s_test\n", spec->name);
    fprintf(f, "\t./%s_test --bench\n\n", spec->name);
    fprintf(f, ".PHONY: all clean run bench\n");

    fclose(f);
    return 0;
}

/* Main code generation function */
int codegen_generate(const SoftChipSpec* spec, const CodegenOptions* opts) {
    /* Create output directory */
    mkdir(opts->output_dir, 0755);

    char path[512];

    /* Generate header */
    snprintf(path, sizeof(path), "%s/%s.h", opts->output_dir, spec->name);
    if (generate_header_file(spec, opts, path) != 0) {
        fprintf(stderr, "Error: Failed to generate header\n");
        return -1;
    }
    printf("  %s.h\n", spec->name);

    /* Generate source */
    snprintf(path, sizeof(path), "%s/%s.c", opts->output_dir, spec->name);
    if (generate_source_file(spec, opts, path) != 0) {
        fprintf(stderr, "Error: Failed to generate source\n");
        return -1;
    }
    printf("  %s.c\n", spec->name);

    /* Generate test */
    if (opts->generate_test) {
        snprintf(path, sizeof(path), "%s/%s_test.c", opts->output_dir, spec->name);
        if (generate_test_file(spec, opts, path) != 0) {
            fprintf(stderr, "Error: Failed to generate test\n");
            return -1;
        }
        printf("  %s_test.c\n", spec->name);
    }

    /* Generate Makefile */
    snprintf(path, sizeof(path), "%s/Makefile", opts->output_dir);
    if (generate_makefile(spec, opts, path) != 0) {
        fprintf(stderr, "Error: Failed to generate Makefile\n");
        return -1;
    }
    printf("  Makefile\n");

    /* Generate linear layers if present */
    if (spec->num_linear_layers > 0) {
        snprintf(path, sizeof(path), "%s/%s_linear.h", opts->output_dir, spec->name);
        if (generate_linear_layers(spec, opts, path) != 0) {
            fprintf(stderr, "Error: Failed to generate linear layers\n");
            return -1;
        }
        printf("  %s_linear.h (%d Linear Kingdom layers)\n", spec->name, spec->num_linear_layers);
    }

    return 0;
}

/* Generate Linear Kingdom layers using linear_forge */
int generate_linear_layers(const SoftChipSpec* spec, const CodegenOptions* opts,
                           const char* filename) {
    if (spec->num_linear_layers == 0) {
        return 0;  /* Nothing to generate */
    }

    FILE* f = fopen(filename, "w");
    if (!f) return -1;

    char timestamp[64];
    get_timestamp(timestamp, sizeof(timestamp));

    fprintf(f, "/*\n");
    fprintf(f, " * %s_linear.h — Linear Kingdom Forged Kernels\n", spec->name);
    fprintf(f, " *\n");
    fprintf(f, " * Auto-generated by trix forge\n");
    fprintf(f, " * Generated: %s\n", timestamp);
    fprintf(f, " * Target: %s\n", target_name(opts->target));
    fprintf(f, " *\n");
    fprintf(f, " * \"The SDOT instruction IS the Prime.\"\n");
    fprintf(f, " */\n\n");

    fprintf(f, "#ifndef %s_LINEAR_H\n", spec->name);
    fprintf(f, "#define %s_LINEAR_H\n\n", spec->name);

    fprintf(f, "#include <stdint.h>\n");
    if (opts->target == TARGET_NEON) {
        fprintf(f, "#include <arm_neon.h>\n");
    }
    fprintf(f, "\n");

    /* Generate each linear layer */
    for (int i = 0; i < spec->num_linear_layers; i++) {
        const LinearLayerSpec* layer = &spec->linear_layers[i];

        fprintf(f, "/* ═══════════════════════════════════════════════════════════════\n");
        fprintf(f, " * Layer: %s\n", layer->name);
        fprintf(f, " * Dimensions: %d -> %d\n", layer->input_dim, layer->output_dim);
        fprintf(f, " * ═══════════════════════════════════════════════════════════════ */\n\n");

        /* Create AggregateShapeSpec for linear_forge */
        AggregateShapeSpec forge_spec = {
            .K = layer->input_dim,
            .N = layer->output_dim,
            .weights = NULL,  /* Will be loaded from file at runtime */
            .weights_size = 0,
            .quant = QUANT_INT8,
            .bias = NULL,
            .activation = ACT_NONE,
        };
        strncpy(forge_spec.name, layer->name, sizeof(forge_spec.name) - 1);

        /* Set activation based on layer spec */
        switch (layer->activation) {
            case LINEAR_ACT_RELU: forge_spec.activation = ACT_RELU; break;
            case LINEAR_ACT_SIGMOID: forge_spec.activation = ACT_SIGMOID; break;
            case LINEAR_ACT_TANH: forge_spec.activation = ACT_TANH; break;
            case LINEAR_ACT_GELU: forge_spec.activation = ACT_GELU; break;
            case LINEAR_ACT_SOFTMAX: forge_spec.activation = ACT_SOFTMAX; break;
            default: forge_spec.activation = ACT_NONE; break;
        }

        /* Set strategy based on target */
        if (opts->target == TARGET_NEON) {
            forge_spec.strategy = FORGE_STRATEGY_NEON_BLOCK8_K64;  /* Best performance */
        } else {
            forge_spec.strategy = FORGE_STRATEGY_C_PORTABLE;
        }

        /* Generate the kernel code into the file */
        char kernel_buf[128 * 1024];
        size_t len = forge_kernel_to_string(&forge_spec, kernel_buf, sizeof(kernel_buf));
        if (len > 0) {
            /* Strip the header comment and includes (already added above) */
            /* Find the static const or void line */
            char* start = strstr(kernel_buf, "static const");
            if (!start) start = strstr(kernel_buf, "void ");
            if (start) {
                fprintf(f, "%s\n", start);
            } else {
                fprintf(f, "%s\n", kernel_buf);
            }
        }

        fprintf(f, "\n");
    }

    fprintf(f, "#endif /* %s_LINEAR_H */\n", spec->name);

    fclose(f);
    return 0;
}

/* Target-specific entry points */
int codegen_c(const SoftChipSpec* spec, const CodegenOptions* opts) {
    CodegenOptions c_opts = *opts;
    c_opts.target = TARGET_C;
    return codegen_generate(spec, &c_opts);
}

int codegen_neon(const SoftChipSpec* spec, const CodegenOptions* opts) {
    CodegenOptions neon_opts = *opts;
    neon_opts.target = TARGET_NEON;
    return codegen_generate(spec, &neon_opts);
}
