#!/usr/bin/env python3
"""
lnn2trix.py — Liquid Neural Network to TriX Compiler

Converts trained LNN/CfC weights into frozen TriX C code.

"Stop simulating. Start casting."

Usage:
    python lnn2trix.py model.pt --name=my_liquid_chip
    python lnn2trix.py model.pt --name=driver --dt=0.01 --fixed

Inputs:
    - PyTorch state dict with CfC weights
    - Or: NumPy .npz file with weight arrays

Outputs:
    - {name}_weights.h    Frozen weight arrays
    - {name}_chip.h       Ready-to-use CfC chip
    - {name}_chip.c       Optional standalone implementation

Created by: Tripp + Claude
Date: January 2026
"""

import argparse
import json
import struct
import sys
from pathlib import Path
from datetime import datetime

# Try to import torch, fall back to numpy-only mode
try:
    import torch
    HAS_TORCH = True
except ImportError:
    HAS_TORCH = False

try:
    import numpy as np
    HAS_NUMPY = True
except ImportError:
    HAS_NUMPY = False


def float_to_c_array(arr, name, indent="    "):
    """Convert numpy array to C static const array."""
    flat = arr.flatten()
    lines = [f"static const float {name}[{len(flat)}] = {{"]

    # Format in rows of 8
    row = []
    for i, val in enumerate(flat):
        row.append(f"{val:.8f}f")
        if len(row) == 8 or i == len(flat) - 1:
            suffix = "," if i < len(flat) - 1 else ""
            lines.append(indent + ", ".join(row) + suffix)
            row = []

    lines.append("};")
    return "\n".join(lines)


def extract_cfc_weights_torch(state_dict):
    """Extract CfC weights from PyTorch state dict."""
    weights = {}

    # Common naming patterns in ncps/liquid libraries
    patterns = {
        'W_gate': ['gate.weight', 'wiring.gate_weight', 'ff1.weight'],
        'b_gate': ['gate.bias', 'wiring.gate_bias', 'ff1.bias'],
        'W_cand': ['candidate.weight', 'wiring.cand_weight', 'ff2.weight'],
        'b_cand': ['candidate.bias', 'wiring.cand_bias', 'ff2.bias'],
        'W_out': ['output.weight', 'readout.weight', 'fc.weight'],
        'b_out': ['output.bias', 'readout.bias', 'fc.bias'],
        'tau': ['tau', 'time_constant', 'timescale'],
    }

    for key, patterns_list in patterns.items():
        for pattern in patterns_list:
            for sd_key, tensor in state_dict.items():
                if pattern in sd_key.lower():
                    weights[key] = tensor.detach().cpu().numpy()
                    break
            if key in weights:
                break

    return weights


def extract_cfc_weights_numpy(npz_file):
    """Extract CfC weights from NumPy .npz file."""
    data = np.load(npz_file)
    weights = {}

    key_map = {
        'W_gate': ['W_gate', 'gate_weight', 'w_gate'],
        'b_gate': ['b_gate', 'gate_bias', 'bias_gate'],
        'W_cand': ['W_cand', 'cand_weight', 'w_cand', 'W_candidate'],
        'b_cand': ['b_cand', 'cand_bias', 'bias_cand', 'b_candidate'],
        'W_out': ['W_out', 'output_weight', 'w_out', 'W_output'],
        'b_out': ['b_out', 'output_bias', 'b_output'],
        'tau': ['tau', 'time_constant'],
    }

    for key, patterns in key_map.items():
        for pattern in patterns:
            if pattern in data:
                weights[key] = data[pattern]
                break

    return weights


def generate_weights_header(weights, name, dt=None):
    """Generate C header with frozen weights."""

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")

    # Infer dimensions
    if 'W_gate' in weights:
        hidden_dim, concat_dim = weights['W_gate'].shape
        # concat_dim = input_dim + hidden_dim
        input_dim = concat_dim - hidden_dim
    else:
        raise ValueError("Missing W_gate weights")

    output_dim = weights.get('W_out', np.zeros((1, hidden_dim))).shape[0]

    lines = [
        f"/*",
        f" * {name}_weights.h — Frozen CfC Weights",
        f" *",
        f" * Auto-generated by lnn2trix.py",
        f" * Date: {timestamp}",
        f" *",
        f" * Dimensions:",
        f" *   Input:  {input_dim}",
        f" *   Hidden: {hidden_dim}",
        f" *   Output: {output_dim}",
        f" *",
        f" * \"Learned routing, frozen forever.\"",
        f" */",
        f"",
        f"#ifndef {name.upper()}_WEIGHTS_H",
        f"#define {name.upper()}_WEIGHTS_H",
        f"",
        f"#define {name.upper()}_INPUT_DIM  {input_dim}",
        f"#define {name.upper()}_HIDDEN_DIM {hidden_dim}",
        f"#define {name.upper()}_OUTPUT_DIM {output_dim}",
        f"",
    ]

    # Gate weights
    lines.append(f"/* Gate weights: sigmoid(W_gate @ [x; h] + b_gate) */")
    lines.append(float_to_c_array(weights['W_gate'], f"{name}_W_gate"))
    lines.append("")
    lines.append(float_to_c_array(weights['b_gate'], f"{name}_b_gate"))
    lines.append("")

    # Candidate weights
    lines.append(f"/* Candidate weights: tanh(W_cand @ [x; h] + b_cand) */")
    lines.append(float_to_c_array(weights['W_cand'], f"{name}_W_cand"))
    lines.append("")
    lines.append(float_to_c_array(weights['b_cand'], f"{name}_b_cand"))
    lines.append("")

    # Time constants
    if 'tau' in weights:
        lines.append(f"/* Time constants (decay rate) */")
        lines.append(float_to_c_array(weights['tau'], f"{name}_tau"))
        lines.append("")
        tau_shared = weights['tau'].size == 1
    else:
        # Default tau = 1.0
        lines.append(f"/* Default time constant */")
        lines.append(f"static const float {name}_tau[1] = {{ 1.0f }};")
        lines.append("")
        tau_shared = True

    # Precomputed decay (if dt provided)
    if dt is not None:
        lines.append(f"/* Precomputed decay: exp(-dt/tau) for dt={dt} */")
        tau = weights.get('tau', np.array([1.0]))
        if tau.size == 1:
            decay = np.full(hidden_dim, np.exp(-dt / tau[0]))
        else:
            decay = np.exp(-dt / tau)
        lines.append(float_to_c_array(decay, f"{name}_decay"))
        lines.append("")

    # Output projection
    # Note: W_out stored as [hidden_dim, output_dim] for GEMM: h @ W_out
    if 'W_out' in weights:
        lines.append(f"/* Output projection: h @ W_out + b_out */")
        # Transpose W_out from [output_dim, hidden_dim] to [hidden_dim, output_dim]
        W_out_T = weights['W_out'].T
        lines.append(float_to_c_array(W_out_T, f"{name}_W_out"))
        lines.append("")
        lines.append(float_to_c_array(weights['b_out'], f"{name}_b_out"))
        lines.append("")

    lines.append(f"#endif /* {name.upper()}_WEIGHTS_H */")

    return "\n".join(lines), {
        'input_dim': input_dim,
        'hidden_dim': hidden_dim,
        'output_dim': output_dim,
        'tau_shared': tau_shared,
        'has_output': 'W_out' in weights,
        'has_precomputed_decay': dt is not None,
    }


def generate_chip_header(name, dims, dt=None):
    """Generate ready-to-use chip header."""

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")

    lines = [
        f"/*",
        f" * {name}_chip.h — Frozen CfC Soft Chip",
        f" *",
        f" * Auto-generated by lnn2trix.py",
        f" * Date: {timestamp}",
        f" *",
        f" * This is a complete, self-contained CfC chip.",
        f" * Include this file and call {name}_infer().",
        f" *",
        f" * \"Solid-state fluid dynamics.\"",
        f" */",
        f"",
        f"#ifndef {name.upper()}_CHIP_H",
        f"#define {name.upper()}_CHIP_H",
        f"",
        f"#include \"trixc/cfc_shapes.h\"",
        f"#include \"{name}_weights.h\"",
        f"",
    ]

    # Parameter struct initialization
    if dims['has_precomputed_decay']:
        lines.extend([
            f"/* CfC cell parameters (fixed time step) */",
            f"static const CfCParamsFixed {name}_cell_params = {{",
            f"    .input_dim  = {name.upper()}_INPUT_DIM,",
            f"    .hidden_dim = {name.upper()}_HIDDEN_DIM,",
            f"    .W_gate     = {name}_W_gate,",
            f"    .b_gate     = {name}_b_gate,",
            f"    .W_cand     = {name}_W_cand,",
            f"    .b_cand     = {name}_b_cand,",
            f"    .decay      = {name}_decay,",
            f"}};",
            f"",
        ])
    else:
        lines.extend([
            f"/* CfC cell parameters */",
            f"static const CfCParams {name}_cell_params = {{",
            f"    .input_dim  = {name.upper()}_INPUT_DIM,",
            f"    .hidden_dim = {name.upper()}_HIDDEN_DIM,",
            f"    .W_gate     = {name}_W_gate,",
            f"    .b_gate     = {name}_b_gate,",
            f"    .W_cand     = {name}_W_cand,",
            f"    .b_cand     = {name}_b_cand,",
            f"    .tau        = {name}_tau,",
            f"    .tau_shared = {'1' if dims['tau_shared'] else '0'},",
            f"}};",
            f"",
        ])

    if dims['has_output']:
        lines.extend([
            f"/* Output projection parameters */",
            f"static const CfCOutputParams {name}_output_params = {{",
            f"    .hidden_dim = {name.upper()}_HIDDEN_DIM,",
            f"    .output_dim = {name.upper()}_OUTPUT_DIM,",
            f"    .W_out      = {name}_W_out,",
            f"    .b_out      = {name}_b_out,",
            f"}};",
            f"",
        ])

    # Convenience inference function
    lines.extend([
        f"/*",
        f" * {name}_step — Process one time step",
        f" *",
        f" * @param x       Input signal [{name.upper()}_INPUT_DIM]",
        f" * @param h_prev  Previous hidden state [{name.upper()}_HIDDEN_DIM]",
    ])

    if not dims['has_precomputed_decay']:
        lines.append(f" * @param dt      Time delta")

    lines.extend([
        f" * @param h_new   Output hidden state [{name.upper()}_HIDDEN_DIM]",
        f" */",
    ])

    if dims['has_precomputed_decay']:
        lines.extend([
            f"static inline void {name}_step(",
            f"    const float* x,",
            f"    const float* h_prev,",
            f"    float* h_new",
            f") {{",
            f"    trix_cfc_cell_fixed(x, h_prev, &{name}_cell_params, h_new);",
            f"}}",
        ])
    else:
        lines.extend([
            f"static inline void {name}_step(",
            f"    const float* x,",
            f"    const float* h_prev,",
            f"    float dt,",
            f"    float* h_new",
            f") {{",
            f"    trix_cfc_cell(x, h_prev, dt, &{name}_cell_params, h_new);",
            f"}}",
        ])

    lines.append("")

    if dims['has_output']:
        lines.extend([
            f"/*",
            f" * {name}_classify — Get class probabilities from hidden state",
            f" */",
            f"static inline void {name}_classify(",
            f"    const float* h,",
            f"    float* probs",
            f") {{",
            f"    trix_cfc_output_softmax(h, &{name}_output_params, probs);",
            f"}}",
            f"",
        ])

    lines.append(f"#endif /* {name.upper()}_CHIP_H */")

    return "\n".join(lines)


def create_example_weights(input_dim=4, hidden_dim=8, output_dim=3):
    """Create example random weights for testing."""
    np.random.seed(42)

    concat_dim = input_dim + hidden_dim

    # Xavier initialization
    gate_scale = np.sqrt(2.0 / (concat_dim + hidden_dim))
    cand_scale = np.sqrt(2.0 / (concat_dim + hidden_dim))
    out_scale = np.sqrt(2.0 / (hidden_dim + output_dim))

    return {
        'W_gate': np.random.randn(hidden_dim, concat_dim).astype(np.float32) * gate_scale,
        'b_gate': np.zeros(hidden_dim, dtype=np.float32),
        'W_cand': np.random.randn(hidden_dim, concat_dim).astype(np.float32) * cand_scale,
        'b_cand': np.zeros(hidden_dim, dtype=np.float32),
        'W_out': np.random.randn(output_dim, hidden_dim).astype(np.float32) * out_scale,
        'b_out': np.zeros(output_dim, dtype=np.float32),
        'tau': np.ones(1, dtype=np.float32),  # Shared tau
    }


def main():
    parser = argparse.ArgumentParser(
        description="Compile LNN/CfC weights to TriX frozen C code",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
    # From PyTorch checkpoint
    python lnn2trix.py model.pt --name=my_chip

    # From NumPy weights
    python lnn2trix.py weights.npz --name=driver

    # With fixed time step (precompute decay)
    python lnn2trix.py model.pt --name=sensor --dt=0.01 --fixed

    # Create example weights for testing
    python lnn2trix.py --example --name=test_chip
        """
    )

    parser.add_argument('input', nargs='?', help='Input file (.pt or .npz)')
    parser.add_argument('--name', required=True, help='Chip name')
    parser.add_argument('--output', '-o', default='.', help='Output directory')
    parser.add_argument('--dt', type=float, help='Fixed time step (precomputes decay)')
    parser.add_argument('--fixed', action='store_true', help='Use fixed time step mode')
    parser.add_argument('--example', action='store_true', help='Generate example weights')
    parser.add_argument('--input-dim', type=int, default=4, help='Input dim for example')
    parser.add_argument('--hidden-dim', type=int, default=8, help='Hidden dim for example')
    parser.add_argument('--output-dim', type=int, default=3, help='Output dim for example')

    args = parser.parse_args()

    # Validate
    if not args.example and not args.input:
        parser.error("Either provide an input file or use --example")

    if args.fixed and args.dt is None:
        parser.error("--fixed requires --dt=<value>")

    # Load weights
    if args.example:
        if not HAS_NUMPY:
            print("Error: NumPy required for --example mode")
            sys.exit(1)
        print(f"Generating example weights ({args.input_dim}→{args.hidden_dim}→{args.output_dim})")
        weights = create_example_weights(args.input_dim, args.hidden_dim, args.output_dim)
    elif args.input.endswith('.pt') or args.input.endswith('.pth'):
        if not HAS_TORCH:
            print("Error: PyTorch required to load .pt files")
            sys.exit(1)
        print(f"Loading PyTorch checkpoint: {args.input}")
        state_dict = torch.load(args.input, map_location='cpu')
        if 'state_dict' in state_dict:
            state_dict = state_dict['state_dict']
        weights = extract_cfc_weights_torch(state_dict)
    elif args.input.endswith('.npz'):
        if not HAS_NUMPY:
            print("Error: NumPy required to load .npz files")
            sys.exit(1)
        print(f"Loading NumPy weights: {args.input}")
        weights = extract_cfc_weights_numpy(args.input)
    else:
        print(f"Error: Unknown file format: {args.input}")
        sys.exit(1)

    # Generate headers
    dt = args.dt if args.fixed else None

    print(f"Generating frozen weights...")
    weights_header, dims = generate_weights_header(weights, args.name, dt)

    print(f"Generating chip header...")
    chip_header = generate_chip_header(args.name, dims, dt)

    # Write outputs
    output_dir = Path(args.output)
    output_dir.mkdir(parents=True, exist_ok=True)

    weights_path = output_dir / f"{args.name}_weights.h"
    chip_path = output_dir / f"{args.name}_chip.h"

    with open(weights_path, 'w') as f:
        f.write(weights_header)
    print(f"  → {weights_path}")

    with open(chip_path, 'w') as f:
        f.write(chip_header)
    print(f"  → {chip_path}")

    # Summary
    print()
    print("╭──────────────────────────────────────────────────────────────╮")
    print(f"│  CfC Chip: {args.name:<49} │")
    print("├──────────────────────────────────────────────────────────────┤")
    print(f"│  Input dimension:  {dims['input_dim']:<41} │")
    print(f"│  Hidden dimension: {dims['hidden_dim']:<41} │")
    print(f"│  Output dimension: {dims['output_dim']:<41} │")
    print(f"│  Time step mode:   {'Fixed' if dt else 'Variable':<41} │")
    print("╰──────────────────────────────────────────────────────────────╯")
    print()
    print("To use:")
    print(f"  #include \"{args.name}_chip.h\"")
    print()
    print(f"  float h[{args.name.upper()}_HIDDEN_DIM] = {{0}};")
    print(f"  float x[{args.name.upper()}_INPUT_DIM];")
    print()
    if dt:
        print(f"  {args.name}_step(x, h, h);  // Fixed dt={dt}")
    else:
        print(f"  {args.name}_step(x, h, dt, h);")
    print()


if __name__ == '__main__':
    main()
