/*
 * cfc_test.h — Soft Chip: cfc_test
 *
 * Auto-generated by trix forge
 * Generated: 2026-01-26 17:01:07
 * Target: neon
 *
 * DO NOT EDIT — Regenerate from .trix spec
 */

#ifndef CFC_TEST_H
#define CFC_TEST_H

#include <stdint.h>
#include <stddef.h>

/* State size */
#define CFC_TEST_STATE_BITS  512
#define CFC_TEST_STATE_BYTES 64

/* Signature labels */
#define CFC_TEST_UNKNOWN -1

/* Soft chip handle */
typedef struct trix_chip trix_chip_t;

/* Inference result */
typedef struct {
    int match;          /* Signature index (-1 = no match) */
    int distance;       /* Hamming distance to match */
    int threshold;      /* Threshold that was used */
    const char* label;  /* Human-readable label */
    uint32_t trace_tick_start; /* HSOS tick when inference began (0 = N/A) */
    uint32_t trace_tick_end;   /* HSOS tick when result was selected (0 = N/A) */
} trix_result_t;

/* API */
trix_chip_t* trix_init(void);
trix_result_t trix_infer(trix_chip_t* chip, const uint8_t input[64]);
void trix_reset(trix_chip_t* chip);
void trix_free(trix_chip_t* chip);

/* State access (for debugging) */
const uint8_t* trix_get_state(const trix_chip_t* chip);

#endif /* CFC_TEST_H */
