/*
 * cfc_test_linear.h — Linear Kingdom Forged Kernels
 *
 * Auto-generated by trix forge
 * Generated: 2026-01-26 17:01:07
 * Target: neon
 *
 * "The SDOT instruction IS the Prime."
 */

#ifndef cfc_test_LINEAR_H
#define cfc_test_LINEAR_H

#include <stdint.h>
#include <arm_neon.h>

/* ═══════════════════════════════════════════════════════════════
 * Layer: gate
 * Dimensions: 64 -> 32
 * ═══════════════════════════════════════════════════════════════ */

static const int8_t gate_W[2048] __attribute__((aligned(64))) = {
    /* Weights embedded at forge time */
};

/* TriX Forged Soft-Chip: gate (NEON Block-8-K64) */
/* Topology: K=64, N=32, Strategy=BLOCK8_K64 */
/* Expected: ~170 GOP/s on M4 base */

#include <arm_neon.h>

void gate_forward_neon(const int8_t* x, int32_t* y) {
    const int K_blocks = 1;
    const int block_stride = 8 * 64;  /* 512 bytes per block */

    for (int n = 0; n < 32; n += 8) {
        int nb = n / 8;

        /* --- RESET ACCUMULATORS (8 channels) --- */
        int32x4_t acc0 = vdupq_n_s32(0);
        int32x4_t acc1 = vdupq_n_s32(0);
        int32x4_t acc2 = vdupq_n_s32(0);
        int32x4_t acc3 = vdupq_n_s32(0);
        int32x4_t acc4 = vdupq_n_s32(0);
        int32x4_t acc5 = vdupq_n_s32(0);
        int32x4_t acc6 = vdupq_n_s32(0);
        int32x4_t acc7 = vdupq_n_s32(0);

        const int8_t* a_ptr = x;
        const int8_t* w_base = gate_W + nb * K_blocks * block_stride;

        /* --- SPATIAL FOLD (K dimension, 64 steps per iteration) --- */
        for (int kb = 0; kb < K_blocks; kb++) {
            /* Prefetch 2 blocks ahead */
            if (kb + 2 < K_blocks) {
                __builtin_prefetch(a_ptr + 128, 0, 3);
                __builtin_prefetch(w_base + (kb + 2) * block_stride, 0, 3);
                __builtin_prefetch(w_base + (kb + 2) * block_stride + 256, 0, 3);
            }

            /* Load 64 activation elements (4 x 16) */
            int8x16_t a0 = vld1q_s8(a_ptr + 0);
            int8x16_t a1 = vld1q_s8(a_ptr + 16);
            int8x16_t a2 = vld1q_s8(a_ptr + 32);
            int8x16_t a3 = vld1q_s8(a_ptr + 48);
            a_ptr += 64;

            const int8_t* w_block = w_base + kb * block_stride;

            /* --- PRIME MATCH (8 rows x 4 SDOT each) --- */
            /* Row 0 */
            {
                int8x16_t w = vld1q_s8(w_block + 0 * 64 + 0);
                acc0 = vdotq_s32(acc0, w, a0);
            }
            {
                int8x16_t w = vld1q_s8(w_block + 0 * 64 + 16);
                acc0 = vdotq_s32(acc0, w, a1);
            }
            {
                int8x16_t w = vld1q_s8(w_block + 0 * 64 + 32);
                acc0 = vdotq_s32(acc0, w, a2);
            }
            {
                int8x16_t w = vld1q_s8(w_block + 0 * 64 + 48);
                acc0 = vdotq_s32(acc0, w, a3);
            }
            /* Row 1 */
            {
                int8x16_t w = vld1q_s8(w_block + 1 * 64 + 0);
                acc1 = vdotq_s32(acc1, w, a0);
            }
            {
                int8x16_t w = vld1q_s8(w_block + 1 * 64 + 16);
                acc1 = vdotq_s32(acc1, w, a1);
            }
            {
                int8x16_t w = vld1q_s8(w_block + 1 * 64 + 32);
                acc1 = vdotq_s32(acc1, w, a2);
            }
            {
                int8x16_t w = vld1q_s8(w_block + 1 * 64 + 48);
                acc1 = vdotq_s32(acc1, w, a3);
            }
            /* Row 2 */
            {
                int8x16_t w = vld1q_s8(w_block + 2 * 64 + 0);
                acc2 = vdotq_s32(acc2, w, a0);
            }
            {
                int8x16_t w = vld1q_s8(w_block + 2 * 64 + 16);
                acc2 = vdotq_s32(acc2, w, a1);
            }
            {
                int8x16_t w = vld1q_s8(w_block + 2 * 64 + 32);
                acc2 = vdotq_s32(acc2, w, a2);
            }
            {
                int8x16_t w = vld1q_s8(w_block + 2 * 64 + 48);
                acc2 = vdotq_s32(acc2, w, a3);
            }
            /* Row 3 */
            {
                int8x16_t w = vld1q_s8(w_block + 3 * 64 + 0);
                acc3 = vdotq_s32(acc3, w, a0);
            }
            {
                int8x16_t w = vld1q_s8(w_block + 3 * 64 + 16);
                acc3 = vdotq_s32(acc3, w, a1);
            }
            {
                int8x16_t w = vld1q_s8(w_block + 3 * 64 + 32);
                acc3 = vdotq_s32(acc3, w, a2);
            }
            {
                int8x16_t w = vld1q_s8(w_block + 3 * 64 + 48);
                acc3 = vdotq_s32(acc3, w, a3);
            }
            /* Row 4 */
            {
                int8x16_t w = vld1q_s8(w_block + 4 * 64 + 0);
                acc4 = vdotq_s32(acc4, w, a0);
            }
            {
                int8x16_t w = vld1q_s8(w_block + 4 * 64 + 16);
                acc4 = vdotq_s32(acc4, w, a1);
            }
            {
                int8x16_t w = vld1q_s8(w_block + 4 * 64 + 32);
                acc4 = vdotq_s32(acc4, w, a2);
            }
            {
                int8x16_t w = vld1q_s8(w_block + 4 * 64 + 48);
                acc4 = vdotq_s32(acc4, w, a3);
            }
            /* Row 5 */
            {
                int8x16_t w = vld1q_s8(w_block + 5 * 64 + 0);
                acc5 = vdotq_s32(acc5, w, a0);
            }
            {
                int8x16_t w = vld1q_s8(w_block + 5 * 64 + 16);
                acc5 = vdotq_s32(acc5, w, a1);
            }
            {
                int8x16_t w = vld1q_s8(w_block + 5 * 64 + 32);
                acc5 = vdotq_s32(acc5, w, a2);
            }
            {
                int8x16_t w = vld1q_s8(w_block + 5 * 64 + 48);
                acc5 = vdotq_s32(acc5, w, a3);
            }
            /* Row 6 */
            {
                int8x16_t w = vld1q_s8(w_block + 6 * 64 + 0);
                acc6 = vdotq_s32(acc6, w, a0);
            }
            {
                int8x16_t w = vld1q_s8(w_block + 6 * 64 + 16);
                acc6 = vdotq_s32(acc6, w, a1);
            }
            {
                int8x16_t w = vld1q_s8(w_block + 6 * 64 + 32);
                acc6 = vdotq_s32(acc6, w, a2);
            }
            {
                int8x16_t w = vld1q_s8(w_block + 6 * 64 + 48);
                acc6 = vdotq_s32(acc6, w, a3);
            }
            /* Row 7 */
            {
                int8x16_t w = vld1q_s8(w_block + 7 * 64 + 0);
                acc7 = vdotq_s32(acc7, w, a0);
            }
            {
                int8x16_t w = vld1q_s8(w_block + 7 * 64 + 16);
                acc7 = vdotq_s32(acc7, w, a1);
            }
            {
                int8x16_t w = vld1q_s8(w_block + 7 * 64 + 32);
                acc7 = vdotq_s32(acc7, w, a2);
            }
            {
                int8x16_t w = vld1q_s8(w_block + 7 * 64 + 48);
                acc7 = vdotq_s32(acc7, w, a3);
            }
        }

        /* --- REDUCE & STORE (Circuit Output) --- */
        y[n + 0] = vaddvq_s32(acc0);
        y[n + 1] = vaddvq_s32(acc1);
        y[n + 2] = vaddvq_s32(acc2);
        y[n + 3] = vaddvq_s32(acc3);
        y[n + 4] = vaddvq_s32(acc4);
        y[n + 5] = vaddvq_s32(acc5);
        y[n + 6] = vaddvq_s32(acc6);
        y[n + 7] = vaddvq_s32(acc7);
    }
}



/* ═══════════════════════════════════════════════════════════════
 * Layer: candidate
 * Dimensions: 64 -> 32
 * ═══════════════════════════════════════════════════════════════ */

static const int8_t candidate_W[2048] __attribute__((aligned(64))) = {
    /* Weights embedded at forge time */
};

/* TriX Forged Soft-Chip: candidate (NEON Block-8-K64) */
/* Topology: K=64, N=32, Strategy=BLOCK8_K64 */
/* Expected: ~170 GOP/s on M4 base */

#include <arm_neon.h>

void candidate_forward_neon(const int8_t* x, int32_t* y) {
    const int K_blocks = 1;
    const int block_stride = 8 * 64;  /* 512 bytes per block */

    for (int n = 0; n < 32; n += 8) {
        int nb = n / 8;

        /* --- RESET ACCUMULATORS (8 channels) --- */
        int32x4_t acc0 = vdupq_n_s32(0);
        int32x4_t acc1 = vdupq_n_s32(0);
        int32x4_t acc2 = vdupq_n_s32(0);
        int32x4_t acc3 = vdupq_n_s32(0);
        int32x4_t acc4 = vdupq_n_s32(0);
        int32x4_t acc5 = vdupq_n_s32(0);
        int32x4_t acc6 = vdupq_n_s32(0);
        int32x4_t acc7 = vdupq_n_s32(0);

        const int8_t* a_ptr = x;
        const int8_t* w_base = candidate_W + nb * K_blocks * block_stride;

        /* --- SPATIAL FOLD (K dimension, 64 steps per iteration) --- */
        for (int kb = 0; kb < K_blocks; kb++) {
            /* Prefetch 2 blocks ahead */
            if (kb + 2 < K_blocks) {
                __builtin_prefetch(a_ptr + 128, 0, 3);
                __builtin_prefetch(w_base + (kb + 2) * block_stride, 0, 3);
                __builtin_prefetch(w_base + (kb + 2) * block_stride + 256, 0, 3);
            }

            /* Load 64 activation elements (4 x 16) */
            int8x16_t a0 = vld1q_s8(a_ptr + 0);
            int8x16_t a1 = vld1q_s8(a_ptr + 16);
            int8x16_t a2 = vld1q_s8(a_ptr + 32);
            int8x16_t a3 = vld1q_s8(a_ptr + 48);
            a_ptr += 64;

            const int8_t* w_block = w_base + kb * block_stride;

            /* --- PRIME MATCH (8 rows x 4 SDOT each) --- */
            /* Row 0 */
            {
                int8x16_t w = vld1q_s8(w_block + 0 * 64 + 0);
                acc0 = vdotq_s32(acc0, w, a0);
            }
            {
                int8x16_t w = vld1q_s8(w_block + 0 * 64 + 16);
                acc0 = vdotq_s32(acc0, w, a1);
            }
            {
                int8x16_t w = vld1q_s8(w_block + 0 * 64 + 32);
                acc0 = vdotq_s32(acc0, w, a2);
            }
            {
                int8x16_t w = vld1q_s8(w_block + 0 * 64 + 48);
                acc0 = vdotq_s32(acc0, w, a3);
            }
            /* Row 1 */
            {
                int8x16_t w = vld1q_s8(w_block + 1 * 64 + 0);
                acc1 = vdotq_s32(acc1, w, a0);
            }
            {
                int8x16_t w = vld1q_s8(w_block + 1 * 64 + 16);
                acc1 = vdotq_s32(acc1, w, a1);
            }
            {
                int8x16_t w = vld1q_s8(w_block + 1 * 64 + 32);
                acc1 = vdotq_s32(acc1, w, a2);
            }
            {
                int8x16_t w = vld1q_s8(w_block + 1 * 64 + 48);
                acc1 = vdotq_s32(acc1, w, a3);
            }
            /* Row 2 */
            {
                int8x16_t w = vld1q_s8(w_block + 2 * 64 + 0);
                acc2 = vdotq_s32(acc2, w, a0);
            }
            {
                int8x16_t w = vld1q_s8(w_block + 2 * 64 + 16);
                acc2 = vdotq_s32(acc2, w, a1);
            }
            {
                int8x16_t w = vld1q_s8(w_block + 2 * 64 + 32);
                acc2 = vdotq_s32(acc2, w, a2);
            }
            {
                int8x16_t w = vld1q_s8(w_block + 2 * 64 + 48);
                acc2 = vdotq_s32(acc2, w, a3);
            }
            /* Row 3 */
            {
                int8x16_t w = vld1q_s8(w_block + 3 * 64 + 0);
                acc3 = vdotq_s32(acc3, w, a0);
            }
            {
                int8x16_t w = vld1q_s8(w_block + 3 * 64 + 16);
                acc3 = vdotq_s32(acc3, w, a1);
            }
            {
                int8x16_t w = vld1q_s8(w_block + 3 * 64 + 32);
                acc3 = vdotq_s32(acc3, w, a2);
            }
            {
                int8x16_t w = vld1q_s8(w_block + 3 * 64 + 48);
                acc3 = vdotq_s32(acc3, w, a3);
            }
            /* Row 4 */
            {
                int8x16_t w = vld1q_s8(w_block + 4 * 64 + 0);
                acc4 = vdotq_s32(acc4, w, a0);
            }
            {
                int8x16_t w = vld1q_s8(w_block + 4 * 64 + 16);
                acc4 = vdotq_s32(acc4, w, a1);
            }
            {
                int8x16_t w = vld1q_s8(w_block + 4 * 64 + 32);
                acc4 = vdotq_s32(acc4, w, a2);
            }
            {
                int8x16_t w = vld1q_s8(w_block + 4 * 64 + 48);
                acc4 = vdotq_s32(acc4, w, a3);
            }
            /* Row 5 */
            {
                int8x16_t w = vld1q_s8(w_block + 5 * 64 + 0);
                acc5 = vdotq_s32(acc5, w, a0);
            }
            {
                int8x16_t w = vld1q_s8(w_block + 5 * 64 + 16);
                acc5 = vdotq_s32(acc5, w, a1);
            }
            {
                int8x16_t w = vld1q_s8(w_block + 5 * 64 + 32);
                acc5 = vdotq_s32(acc5, w, a2);
            }
            {
                int8x16_t w = vld1q_s8(w_block + 5 * 64 + 48);
                acc5 = vdotq_s32(acc5, w, a3);
            }
            /* Row 6 */
            {
                int8x16_t w = vld1q_s8(w_block + 6 * 64 + 0);
                acc6 = vdotq_s32(acc6, w, a0);
            }
            {
                int8x16_t w = vld1q_s8(w_block + 6 * 64 + 16);
                acc6 = vdotq_s32(acc6, w, a1);
            }
            {
                int8x16_t w = vld1q_s8(w_block + 6 * 64 + 32);
                acc6 = vdotq_s32(acc6, w, a2);
            }
            {
                int8x16_t w = vld1q_s8(w_block + 6 * 64 + 48);
                acc6 = vdotq_s32(acc6, w, a3);
            }
            /* Row 7 */
            {
                int8x16_t w = vld1q_s8(w_block + 7 * 64 + 0);
                acc7 = vdotq_s32(acc7, w, a0);
            }
            {
                int8x16_t w = vld1q_s8(w_block + 7 * 64 + 16);
                acc7 = vdotq_s32(acc7, w, a1);
            }
            {
                int8x16_t w = vld1q_s8(w_block + 7 * 64 + 32);
                acc7 = vdotq_s32(acc7, w, a2);
            }
            {
                int8x16_t w = vld1q_s8(w_block + 7 * 64 + 48);
                acc7 = vdotq_s32(acc7, w, a3);
            }
        }

        /* --- REDUCE & STORE (Circuit Output) --- */
        y[n + 0] = vaddvq_s32(acc0);
        y[n + 1] = vaddvq_s32(acc1);
        y[n + 2] = vaddvq_s32(acc2);
        y[n + 3] = vaddvq_s32(acc3);
        y[n + 4] = vaddvq_s32(acc4);
        y[n + 5] = vaddvq_s32(acc5);
        y[n + 6] = vaddvq_s32(acc6);
        y[n + 7] = vaddvq_s32(acc7);
    }
}



#endif /* cfc_test_LINEAR_H */
